=head1 Introduction

This script is intended to printout a nice default page if it is included/present in the current directory.

=head2 RULE 1

If so, update(s) is/are made within sub-directorie(s) present(s) in this directory. The initial script is copied in that sub-directory that's how it is updated.

=head2 RULE 2

If you go within one of these sub-directorie(s) then, it becomes current directory and RULE 1 is applied and so on and so fourth!

=head2 FILE README.POD

By default only README.pod is interpreted in the current directory.  To write *.pod scripts go to L<pod|https://perldoc.perl.org/perlpod> documention. Only one README.pod file per directory is allowed but that directory can have as many as *.pod file as needed!

=head1 Technical prerequisites

=over

=item * It is needed to have script interpreter installed at server side.

=item * It is needed to install some more dependencies... To install these dependecies go to L<cpan|https://www.cpan.org/>.

=item * Modification within I<index.cgi> need to be made:

=back

C<< 
my %pathOS = ( 'linux' =E<gt> '/home/sdo/public_html/','darwin' =E<gt> '/Users/sdo/Sites/');
 >>

=over

=item * Deprecated link on repo was made.

=back

=head1 What else to say? Just click me!

https://youtu.be/sYGizBhjti4

=head1 FYI

It is still unstable portage is not over yet. Tested on Linux (Fedora, Ubuntu), Mac OS X (Venture 13.1).
